name: Synchronisation Miroir Public

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurer la clé SSH de destination
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: "${{ secrets.RETO_MIROIR_CLE }}" # Ajout des guillemets pour sécuriser la chaîne

      - name: Pousser le code vers le dépôt public
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          
          git config --global user.name "Netiqui Bot"
          git config --global user.email "bot@netiqui.com"
          
          git remote remove miroir || true
          git remote add miroir git@github.com:gogamenetiqui/Go-Buznes.git
          
          GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=accept-new" git push miroir main --force -v
